title: GitHub Copilot Quickstart Guide
remote_theme: pages-themes/slate@v0.2.0


sidebar:
  - getting-started
  - label: Customization
    children:
      - sidebar
      - search
      - relative-nav
      - additional-config
  - development
